import type { User, Post } from '../types';

// Mock 사용자 데이터
export const mockUsers: User[] = [
  {
    id: '1',
    email: 'test@example.com',
    username: 'traveler123',
    profileImage: 'https://i.pravatar.cc/150?u=1',
    bio: '세계 여행을 사랑하는 여행자',
    followersCount: 1234,
    followingCount: 567,
    postsCount: 42,
    createdAt: new Date().toISOString(),
  },
  {
    id: '2',
    email: 'user2@example.com',
    username: 'worldexplorer',
    profileImage: 'https://i.pravatar.cc/150?u=2',
    bio: '🌍 전 세계를 탐험 중',
    followersCount: 5678,
    followingCount: 890,
    postsCount: 128,
    createdAt: new Date().toISOString(),
  },
  {
    id: '3',
    email: 'user3@example.com',
    username: 'photographer',
    profileImage: 'https://i.pravatar.cc/150?u=3',
    bio: '📸 여행 사진작가',
    followersCount: 9876,
    followingCount: 234,
    postsCount: 256,
    createdAt: new Date().toISOString(),
  },
];

// Mock 게시물 데이터
// Luma AI capture URL 형식: https://lumalabs.ai/capture/{uuid}
// 실제 존재하는 Luma Gaussian Splatting 에셋 사용
export const mockPosts: Post[] = [
  {
    id: '1',
    userId: '2',
    user: mockUsers[1],
    imageUrl: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800',
    image3dUrl: 'https://lumalabs.ai/capture/4da7cf32-865a-4515-8cb9-9dfc574c90c2',
    is3D: true,
    caption: '파리 에펠탑에서 바라본 멋진 석양! 정말 환상적이었어요 🗼✨',
    location: '파리, 프랑스',
    hashtags: ['파리', '에펠탑', '유럽여행', '프랑스'],
    likesCount: 1234,
    commentsCount: 56,
    isLiked: false,
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: '2',
    userId: '3',
    user: mockUsers[2],
    imageUrl: 'https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?w=800',
    is3D: false,
    caption: '산토리니의 아름다운 블루돔 💙 꿈같은 풍경',
    location: '산토리니, 그리스',
    hashtags: ['산토리니', '그리스', '지중해', '여행'],
    likesCount: 2345,
    commentsCount: 89,
    isLiked: true,
    createdAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: '3',
    userId: '2',
    user: mockUsers[1],
    imageUrl: 'https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?w=800',
    image3dUrl: 'https://lumalabs.ai/capture/ca9ea966-ca24-4ec1-ab0f-af665cb546ff',
    is3D: true,
    caption: '일본 후지산의 위엄! 🗻 3D로 보니 더 실감나네요',
    location: '후지산, 일본',
    hashtags: ['일본', '후지산', '자연', '산'],
    likesCount: 3456,
    commentsCount: 123,
    isLiked: false,
    createdAt: new Date(Date.now() - 10800000).toISOString(),
  },
  {
    id: '4',
    userId: '3',
    user: mockUsers[2],
    imageUrl: 'https://images.unsplash.com/photo-1523482580672-f109ba8cb9be?w=800',
    image3dUrl: 'https://lumalabs.ai/capture/d80d4876-cf71-4b8a-8b5b-49ffac44cd4a',
    is3D: true,
    caption: '뉴욕 타임스퀘어의 밤 🌃 정말 눈부셨어요',
    location: '뉴욕, 미국',
    hashtags: ['뉴욕', '타임스퀘어', '미국', '야경'],
    likesCount: 4567,
    commentsCount: 234,
    isLiked: true,
    createdAt: new Date(Date.now() - 14400000).toISOString(),
  },
  {
    id: '5',
    userId: '2',
    user: mockUsers[1],
    imageUrl: 'https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?w=800',
    image3dUrl: 'https://lumalabs.ai/capture/1b5f3e33-3900-4398-8795-b585ae13fd2d',
    is3D: true,
    caption: '페트라의 신전, 역사의 숨결이 느껴지는 곳 🏛️',
    location: '페트라, 요르단',
    hashtags: ['요르단', '페트라', '세계문화유산', '고대유적'],
    likesCount: 5678,
    commentsCount: 345,
    isLiked: false,
    createdAt: new Date(Date.now() - 18000000).toISOString(),
  },
  {
    id: '6',
    userId: '3',
    user: mockUsers[2],
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
    image3dUrl: 'https://lumalabs.ai/capture/b86b7928-f130-40a5-8cac-8095f30eed54',
    is3D: true,
    caption: '노르웨이의 피요르드 🏔️ 자연의 경이로움',
    location: '노르웨이',
    hashtags: ['노르웨이', '피요르드', '자연', '북유럽'],
    likesCount: 6789,
    commentsCount: 456,
    isLiked: false,
    createdAt: new Date(Date.now() - 21600000).toISOString(),
  },
  {
    id: '7',
    userId: '1',
    user: mockUsers[0],
    imageUrl: 'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800',
    image3dUrl: 'https://lumalabs.ai/capture/4da7cf32-865a-4515-8cb9-9dfc574c90c2',
    is3D: true,
    caption: '스위스 알프스의 설원 ❄️ 눈 덮인 산들이 장관이에요',
    location: '스위스',
    hashtags: ['스위스', '알프스', '설원', '산'],
    likesCount: 7890,
    commentsCount: 567,
    isLiked: false,
    createdAt: new Date(Date.now() - 25200000).toISOString(),
  },
  {
    id: '8',
    userId: '2',
    user: mockUsers[1],
    imageUrl: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=800',
    image3dUrl: 'https://lumalabs.ai/capture/ca9ea966-ca24-4ec1-ab0f-af665cb546ff',
    is3D: true,
    caption: '이탈리아 베네치아의 운하 🚤 물 위의 도시',
    location: '베네치아, 이탈리아',
    hashtags: ['베네치아', '이탈리아', '운하', '유럽'],
    likesCount: 8901,
    commentsCount: 678,
    isLiked: true,
    createdAt: new Date(Date.now() - 28800000).toISOString(),
  },
];

// Mock 인증 응답 생성 함수
export function createMockAuthResponse(email: string, username: string) {
  return {
    user: {
      id: '1',
      email,
      username,
      profileImage: 'https://i.pravatar.cc/150?u=mock',
      bio: '여행을 사랑하는 사람',
      followersCount: 0,
      followingCount: 0,
      postsCount: 0,
      createdAt: new Date().toISOString(),
    },
    token: 'mock_token_' + Date.now(),
  };
}

// 딜레이 시뮬레이션 (실제 API 호출처럼 보이게)
export const delay = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));
